# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploits', '0001_initial'),
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exploit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploits.Exploits')),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robo.Robo')),
            ],
        ),
    ]
